# Generated by Django 5.2.1 on 2025-05-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sala', models.CharField(max_length=50)),
                ('capacidade', models.IntegerField()),
                ('sala_imagem', models.ImageField(upload_to='fotos/equipamentos')),
                ('slug', models.SlugField(unique=True)),
                ('descricao_sala', models.TextField()),
            ],
        ),
    ]
