# Generated by Django 5.2.1 on 2025-05-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='preco_por_hora',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='sala_imagem',
            field=models.ImageField(blank=True, upload_to='media/fotos'),
        ),
    ]
