# Generated by Django 5.2.1 on 2025-05-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planos',
            name='tipo_de_sala',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planos',
            name='tipo_plano',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='planos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
