# Generated by Django 5.2.1 on 2025-05-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0002_planos_descricao_planos_tipo_de_sala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='imagens',
            field=models.ImageField(blank=True, upload_to='fotos/planos'),
        ),
    ]
