# Generated by Django 5.2.1 on 2025-05-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_planos_imagens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planos',
            new_name='Plano',
        ),
    ]
