# Generated by Django 5.2.1 on 2025-07-01 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_initial'),
        ('salas', '0002_sala_preco_por_hora_alter_sala_capacidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço Mensal')),
                ('beneficios', models.TextField(blank=True, help_text='Lista os benefícios deste plano', verbose_name='Benefícios Incluídos')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['preco'],
            },
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['data_reserva'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='assinatura_plano',
            field=models.BooleanField(default=False, help_text='Marcar se deseja associar um plano à reserva', verbose_name='Assinar Plano?'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cpf',
            field=models.CharField(help_text='Formato: 000.000.000-00', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(verbose_name='Data da Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_entrada',
            field=models.TimeField(verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_saida',
            field=models.TimeField(verbose_name='Hora de Saída'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_completo',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala_de_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.sala', verbose_name='Sala Reservada'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='plano',
            field=models.ForeignKey(blank=True, help_text='Plano de assinatura escolhido (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.plano', verbose_name='Plano Associado'),
        ),
    ]
