# Generated by Django 5.2.1 on 2025-07-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0004_rename_planos_plano'),
        ('reservas', '0005_plano_alter_reserva_options_reserva_assinatura_plano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='plano',
            field=models.ForeignKey(blank=True, help_text='Plano de assinatura escolhido (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planos.plano', verbose_name='Plano Associado'),
        ),
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
